### ISSUE TITLE
qgis3 support

### ISSUE THREAD

**Issue by xamulap** [qgisinspiretools/qgis-wfs20-client-plugin#16]
any plans for QGIS3 support ? I know it has build in WFS but for some reason it doesn't work for me, with this plugin it works. But I am more and more forced to use QGIS3 

Maybe I would try to do it myself, but not really sure where to start. How much is api of QGIS2 and QGIS3 different.  Any pointers ?

**Comment by ejn** [comment]
Hi Peter, we already have an initial version (beta-quality) supporting QGIS 3 published under https://www.geoportal-mv.de/portal/downloads/plugins/qgis_plugins.zip (install locally via the QGIS Plugin Manager - archive also contains initial versions of the Atom-Feed and Complex GML Info plugins).

There's a few things need tidying up, which I hope to be able to do in the coming days, after which I'll push the code up to GitHub and then we can hopefully get the new version into the official repository.

In the meantime, please feel free to give any feedback on the initial version!

**Comment by xamulap** [comment]
Weeeeee! It works. You saved my day :)

I had little trouble with this 

```
from PyQt5 import QtXml, QtXmlPatterns
ImportError: cannot import name 'QtXmlPatterns'
```

This fixed the problem

`apt install python3-pyqt5.qtxmlpatterns`

I didn't find Configure view for plugin.
And I also noticed that once I click GetFeatures(s) prograsbar stays on 50% , but it seems all polygons are downloaded. 

If you would need any other testing let me know.

**Comment by ejn** [comment]
I've just fixed a load of remaining issues from the migration (and some pre-existing ones), merged the updates into master, and put up a release [0.9.8-beta.1](https://github.com/qgisinspiretools/qgis-wfs20-client-plugin/releases/tag/0.9.8-beta.1)

The dependency on qtxmlpatterns is still there, but hopefully most other things work.

If you have time to test again, that would be great!

**Comment by xamulap** [comment]
Installation was smooth. 

For old problems: 
> 1) didn't find Configure view for plugin.
> 2) noticed that once I click GetFeatures(s) prograsbar stays on 50% , but it seems all polygons are downloaded. 

1) I still cannot find it, it used to be in Plugin -> WFS Client. 
2) I confirm as fixed

**Comment by ejn** [comment]
Thanks for the feedback. The configure view is for me (QGIS 3.10 on Windows) in the "Web"-menu.

**Comment by xamulap** [comment]
It there, sorry. So I would say it is working. Closing thicket
